### ISSUE TITLE
Runs for a bit, then crashes

### ISSUE THREAD

**Issue by ThatBum** [doogle/Journey3Dg#1]
It runs fine at first, but after a short while it crashes seemingly randomly and throws this error in console:
```
Traceback (most recent call last):
  File "<stdin>", line 163, in <module>
  File "<string>", line 3, in <module>
AttributeError: 'SSD1306_SPI_Grey' object has no attribute 'fill'
```
Note that this is running on one of the Thumbys with the new batch of screens. To get the grayscale working I modified ssd1306gray.py as shown [here](https://gist.github.com/AngelJA/7076a0ff19912fc06b2cffff23563d7f). I'm also using the arcade version.

**Comment by doogle** [comment]
Hi,
Can you share your modified ssd1306grey.py?  
About how long is 'a short while'? Does it run for just a few seconds before crashing, or after a few minutes?

**Comment by ThatBum** [comment]
The only changes I made to ssd1306grey.py were to change `SSD1306_SPI_Grey_frame_time_us        = const(4709)` to `SSD1306_SPI_Grey_frame_time_us        = const(6000)` and `self.pre_frame_cmds = bytearray([0xa8,0, 0xd3,52])` to `self.pre_frame_cmds = bytearray([0xa8,1, 0xd3,52])`

It'll usually run for less than 30 seconds but sometimes for a minute or two. I think there's some sort of buffer overflow or out of memory condition happening somewhere. Note that'll crash without the modifications as well, but running with corrupted graphics as shown [here](https://www.youtube.com/watch?v=vlmSkP-Ryqo).

**Comment by doogle** [comment]
Hmm ok. A few things to try that should hopefully help debug this:

1. What's the value of `os.uname().release`?

2. Does it crash (and if so with what output) if you add
```
main(None)
```
to the end of Journey3Dg_main.py and run _that_ file in the code editor instead of Journey3Dg.py? (Remember to remove that line before trying to run it from the main menu again).

3. Can you add a `print(type(disp))` before `disp.fill(0)` in `main()` in Journey3Dg_main.py? If it doesn't crash with that, you could try putting the `print()` in an `if getattr(disp, 'fill', None) is None:` so it only prints the type when the `fill()` method disappears (i.e. just before a crash).

4. Does it crash if you remove the `@micropython.native` decorator to `main()`? (try with and without item 3).

5. Can you comment out all the `player` stuff (creation of the instance and calls to`.start()`, `.frame()`, `.stop()` etc., and maybe also the `MusicPlayer` import) in Journey3Dg_main.py and see if it still crashes?  

6. Try called `random.seed(x)` before running (or add a line near the top) with different values of `x` (but running multiple times with each value) to see if the time-to-crash is consistent with the same random seed. If this crash is due to corruption in somewhere like the framebuffer arrays due to randomly chosen parameters of graphical elements, then maybe there'll be some level of repeatability.

Either way this _is_ weird. An out of memory issue should just result in a normal out-of-memory crash, not a disappearing method. A buffer overflow could be the cause, but then I'd expect it to be a more widely reported issue (although I don't know how many people are trying Journey3Dg on the newer Thumbys). I don't think the display being different should matter here (except visually of course) as there's no data being fed back from the display controller to the microcontroller.

**Comment by ThatBum** [comment]
Think I solved it. I decreased the overclock from 280MHz to 200MHz. It's been going for a half hour now and is still running at an acceptable speed. Guess I didn't win the silicon lottery? I got halfway through your steps before stumbling upon the overclock line, lol. I think a 111% overclock is a bit of a bruh moment, not everyone's thumby is going to run that fast it seems. Maybe turn it down a little for the arcade release?

Speaking of performance, you know a way to query the framerate of the demo? So I can see exactly how fast I can get my thumby to run.

Finally, a suggestion. Might want to rework this demo to work with the [thumbyGrayscale](https://github.com/Timendus/thumby-grayscale) library. It works in the emulator and it's looking like it'll be incorporated into the official API soon. And a fix for the new screen that's above and beyond the current hack is forthcoming.

**Comment by doogle** [comment]
Hmm, that does seem to be unlucky; like I said this is the first time I've heard about this issue. Then again, if it does run at lower freqs then that's of course a good thing. Feel free to submit a PR for the arcade (and here if you want) with the freq change.

It's removed from the arcade version, but the version in this repo has a (usually commented out) FPS indicator. You can uncomment the relevant line in `main()` (in Journey3Dg_main.py) to enable it.

The greyscale code in this demo is based on the initial code I wrote to implement the display hack I came up with for frame synchronisation. That code was also used in the thumbyGrayscale library, with various changes to make it look more like the Thumby Graphics class than the SSD1306 driver (along with some other refactoring). By the time the two drivers diverged further with the decision change how the bitplanes mapped to greys, I had already written enough of the demo that I decided to stick with the existing driver.  
The driver in the demo also ended up with some other changes around init that wouldn't have made sense in thumbyGrayscale, but some later changes were added to both, such as the direct SPI and timer register access stuff in the thread function, which I wrote to avoid issues when writing to flash on the main thread.

At the moment I don't have the time or inclination to rewrite the demo to use the thumbyGrayscale library, but I'd be happy for someone else to tackle that and submit a PR. Tbh once a full fix for the new screen is in place, it might just be easier to absorb the relevant changes to the demo's driver.

In terms of emulator support, I was never really concerned about that as the original demo (still with dithering but without greyscale) never ran properly in the emulator anyway, even on a powerful PC. I can get Journey3Dg to run fine with a small SDL layer and some other bits and pieces to make CPython look like micropython (this is how I generated the looping arcade video), but the code editor's emulator is unlikely to run anywhere close to realtime.
